name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "/home/ubuntu/MiniWeTransfer" ]; then
              git clone https://github.com/${{ github.repository }}.git /home/ubuntu/MiniWeTransfer
            fi
            cd /home/ubuntu/MiniWeTransfer
            git pull origin main
            
            echo "PORT=5000" > backend/.env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> backend/.env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> backend/.env
            echo "AWS_REGION=us-east-1" >> backend/.env
            echo "S3_BUCKET_NAME=miniwetransfer-uploads-nilad-demo-123" >> backend/.env
            echo "DYNAMODB_TABLE_NAME=MiniWeTransferFiles" >> backend/.env

            sudo docker-compose down || true
            sudo docker-compose up -d --build
